Step 1 solution upgrade
inferno-framework/tutorial-test-kit pull request #3
Opened 2024-09-25 15:59 UTC by elsaperelli

## Summary
This PR updates the Inferno template version in step-1-solution branch. It includes the solution to step-1 of the tutorial.

## Testing
Run locally with Docker:
- Run `./run.sh` in this repository
- Navigate to `http://localhost`
- Run test kit with the following inputs:
    - FHIR Base Server URL: `https://inferno.healthit.gov/reference-server/r4`
    - access_token: `SAMPLE_TOKEN`
    - Patient ID: `85`
- You should get the following results:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/b47458c9-cce5-4675-b98d-620f16ac1b0e">

Also run with Ruby.

2024-10-08 16:47 UTC, emichaud998 commented
<img width="602" alt="Screenshot 2024-10-08 at 12 46 30 PM" src="https://github.com/user-attachments/assets/dd5c383a-ec1b-4b61-ab3b-d82198f3670d">

Access token input is showing up twice

2024-10-08 16:48 UTC, emichaud998 commented on lib/inferno_template.rb
>      input :access_token
Remove this line

2024-10-08 17:00 UTC, emichaud998 commented on lib/inferno_template.rb
> +
I think we want to remove this input and just have the access_token input instead. Or change the tutorial to say to add a new Oauth Credentials input

2024-10-08 17:00 UTC, emichaud998 commented on lib/inferno_template.rb
> +      oauth_credentials :credentials
We would remove this if we got rid of the oauth_credentials input

2024-10-09 15:31 UTC, elsaperelli commented on lib/inferno_template.rb
> +
Decided to leave for now and create separate task!

2024-10-09 16:09 UTC, emichaud998 approved these changes
Looks good!

2024-10-09 16:14 UTC, emichaud998 requested changes
Oh wait just noticed the spec tests are failing, they are all skipping, probably because they need to pass in the access token input

2024-10-09 16:16 UTC, emichaud998 commented on spec/inferno_template/patient_group_spec.rb
> +      result = run(test, url: url)
Since the access token input is required, you have to pass in that input as well in all the spec tests

2024-10-10 17:03 UTC, emichaud998 approved these changes
Looks good!

2024-10-23 15:48 UTC, merged